kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
rules:
  - verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'patch'
      - 'update'
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - 'create'
      - 'patch'
      - 'update'
    apiGroups:
      - route.openshift.io
    resources:
      - routes/custom-host
  - verbs:
      - 'get'
      - 'list'
      - 'watch'
      - 'patch'
      - 'update'
      - 'create'
    apiGroups:
      - cert-manager.io
    resources:
      - certificates
  - verbs:
      - 'get'
    apiGroups:
      - ''
    resources:
      - secrets
  - apiGroups: 
      - "events.k8s.io"
    resources: 
      - "events"
    verbs: 
      - "create"
