apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" . }}
  namespace: {{ .Values.cert_manager_namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
