image:
  repository: ghcr.io/its4u/cert-manager-routes-controller
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: "cm-routes-controller"

autoscaling:
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

service:
  type: ClusterIP
  port: 3000

cert_manager_namespace: "cert-manager"
