name: Publish a new release

on:
  push:
    tags:
      - "v*"
      
jobs:

  realease:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    
    - name: Update version in Chart.yaml and in Cargo.toml
      run: |
        sed -i "s/version: .*/version: \"${{ github.ref_name }}\"/g" ./charts/Chart.yaml
        sed -i "s/appVersion: .*/appVersion: \"${{ github.ref_name }}\"/g" ./charts/Chart.yaml
        sed -i "0,/version = .*/s//version = \"${{ github.ref_name }}\"/" ./ctrl/Cargo.toml

    - name: Commit modified files
      uses: EndBug/add-and-commit@v9.1.3
      with:
        add: '-f charts/Chart.yaml ctrl/Cargo.toml'
        message: 'Update version to ${{ github.ref_name }}'
        tag: '${{ github.ref_name }} --force'
        tag_push: '--force'
        push: "origin HEAD:main"     
        
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    
    - name: Build the Docker image and push it to ghcr.io
      run: |
        docker build . --file Dockerfile --tag ghcr.io/its4u/cert-manager-routes-controller:${{  github.ref_name }}
        docker push ghcr.io/its4u/cert-manager-routes-controller:${{  github.ref_name }}

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
